services:
  database:
    image: mariadb:11-noble # https://hub.docker.com/_/mariadb
    networks:
      - backend
    environment:
      - MARIADB_DATABASE=RESTAURANTS
      - MARIADB_ROOT_PASSWORD=root-password
    ports:
      - "3306:3306"
    volumes:
      # https://hub.docker.com/_/mariadb @ Initializing the database contents
      - "./create-db-RESTAURANTS.sql:/docker-entrypoint-initdb.d/1.sql"
      - "./database-data:/var/lib/mysql"
    # create a healthcheck to determine when the database is up and running
    # only after the healthcheck is OK, start the web-application --> @see depends_on
    healthcheck:
      test: ["CMD", "mariadb", "--user=root", "--password=root-password", "--execute", "use", "RESTAURANTS"]
      interval: 1s
      timeout: 10s
      retries: 5
      start_period: 60s

  app:
    build:
      context: ../
      dockerfile: ./container/Dockerfile
    image: restaurant_app
    networks:
      - backend
      - frontend
    ports:
      - "9000:9000"
    # https://docs.docker.com/compose/how-tos/environment-variables/set-environment-variables/
    # see 12-factor app: https://12factor.net/config
    environment:
      FLASK_ENV: "production"
      FLASK_DEBUG: 0
      # the configuration-logic "overwrites" the config values of the config-file with environment-variable values
      # infrastructure/config.py:Config.load_from_data
      SECRET_KEY: "CUi0w3Ezqn8GZinmS@H*YMKlWVVVJaRH"
      # the hostname "database" refers to the service with name database - see above
      # SYNTAX:
      # type :// user : password (ensure URL-encoding) @ host : port / database name ? options
      # https://docs.sqlalchemy.org/en/20/dialects/mysql.html
      DATABASE_URI: "mariadb+pymysql://root:root-password@database:3306/RESTAURANTS?charset=utf8mb4"
    depends_on:
      database:
        condition: service_healthy
        restart: true

networks:
  backend:
  frontend:
