services:
  database:
    image: mariadb:11-noble # https://hub.docker.com/_/mariadb
    # would be better to have a local folder where the database files are persisted
    #volumes:
    #- ./database-data:/var/lib/mysql
    networks:
      - backend
    environment:
      - MARIADB_DATABASE=RESTAURANTS
      - MARIADB_ROOT_PASSWORD=root-password
    ports:
      - "3306:3306"
    volumes:
      # https://hub.docker.com/_/mariadb @ Initializing the database contents
      - "./create-db-RESTAURANTS.sql:/docker-entrypoint-initdb.d/1.sql"
    # create a healthcheck to determine when the database is up and running
    # only after the healthcheck is OK, start the web-application --> @see depends_on
    healthcheck:
      test: ["CMD", "mariadb", "--user=root", "--password=root-password", "--execute", "use", "RESTAURANTS"]
      interval: 1s
      timeout: 10s
      retries: 5
      start_period: 60s

  app:
    build:
      context: ../
      dockerfile: ./container/Dockerfile
    image: restaurant_app
    networks:
      - backend
      - frontend
    ports:
      - "9000:9000"
    environment:
      - ENV FLASK_ENV=production
      - ENV FLASK_DEBUG=0
      - ENV DATABASE_URI="mariadb+pymysql://root:root-password/RESTAURANTS?charset=utf8mb4"
    depends_on:
      database:
        condition: service_healthy
        restart: true

networks:
  backend:
  frontend:
