@startuml packages_restaurant_app
set namespaceSeparator none
package "restaurant_app" as restaurant_app #77AADD {
}
package "restaurant_app.infrastructure" as restaurant_app.infrastructure #99DDFF {
}
package "restaurant_app.infrastructure.cache" as restaurant_app.infrastructure.cache #99DDFF {
}
package "restaurant_app.infrastructure.config" as restaurant_app.infrastructure.config #99DDFF {
}
package "restaurant_app.infrastructure.container" as restaurant_app.infrastructure.container #99DDFF {
}
package "restaurant_app.infrastructure.environment" as restaurant_app.infrastructure.environment #99DDFF {
}
package "restaurant_app.infrastructure.logger" as restaurant_app.infrastructure.logger #99DDFF {
}
package "restaurant_app.infrastructure.memory_cache" as restaurant_app.infrastructure.memory_cache #99DDFF {
}
package "restaurant_app.infrastructure.memory_cache_test" as restaurant_app.infrastructure.memory_cache_test #99DDFF {
}
package "restaurant_app.reservation" as restaurant_app.reservation #44BB99 {
}
package "restaurant_app.reservation.models" as restaurant_app.reservation.models #44BB99 {
}
package "restaurant_app.reservation.service" as restaurant_app.reservation.service #44BB99 {
}
package "restaurant_app.reservation.service_test" as restaurant_app.reservation.service_test #44BB99 {
}
package "restaurant_app.restaurant" as restaurant_app.restaurant #BBCC33 {
}
package "restaurant_app.restaurant.forms" as restaurant_app.restaurant.forms #BBCC33 {
}
package "restaurant_app.restaurant.models" as restaurant_app.restaurant.models #BBCC33 {
}
package "restaurant_app.restaurant.service" as restaurant_app.restaurant.service #BBCC33 {
}
package "restaurant_app.restaurant.service_model_mapper" as restaurant_app.restaurant.service_model_mapper #BBCC33 {
}
package "restaurant_app.restaurant.service_test" as restaurant_app.restaurant.service_test #BBCC33 {
}
package "restaurant_app.restaurant.views" as restaurant_app.restaurant.views #BBCC33 {
}
package "restaurant_app.store" as restaurant_app.store #AAAA00 {
}
package "restaurant_app.store.base_repository" as restaurant_app.store.base_repository #AAAA00 {
}
package "restaurant_app.store.database" as restaurant_app.store.database #AAAA00 {
}
package "restaurant_app.store.entities" as restaurant_app.store.entities #AAAA00 {
}
package "restaurant_app.store.menu_repository" as restaurant_app.store.menu_repository #AAAA00 {
}
package "restaurant_app.store.menu_repository_test" as restaurant_app.store.menu_repository_test #AAAA00 {
}
package "restaurant_app.store.repository_test_helpers" as restaurant_app.store.repository_test_helpers #AAAA00 {
}
package "restaurant_app.store.reservation_repo" as restaurant_app.store.reservation_repo #AAAA00 {
}
package "restaurant_app.store.reservation_repo_test" as restaurant_app.store.reservation_repo_test #AAAA00 {
}
package "restaurant_app.store.restaurant_repository" as restaurant_app.store.restaurant_repository #AAAA00 {
}
package "restaurant_app.store.restaurant_repository_test" as restaurant_app.store.restaurant_repository_test #AAAA00 {
}
package "restaurant_app.store.table_repository" as restaurant_app.store.table_repository #AAAA00 {
}
package "restaurant_app.store.table_repository_test" as restaurant_app.store.table_repository_test #AAAA00 {
}
restaurant_app --> restaurant_app.infrastructure.config
restaurant_app --> restaurant_app.infrastructure.container
restaurant_app --> restaurant_app.infrastructure.environment
restaurant_app --> restaurant_app.infrastructure.logger
restaurant_app --> restaurant_app.restaurant
restaurant_app.infrastructure.container --> restaurant_app.infrastructure.config
restaurant_app.infrastructure.container --> restaurant_app.infrastructure.memory_cache
restaurant_app.infrastructure.memory_cache --> restaurant_app.infrastructure.cache
restaurant_app.infrastructure.memory_cache_test --> restaurant_app.infrastructure.memory_cache
restaurant_app.reservation.service --> restaurant_app.reservation.models
restaurant_app.reservation.service_test --> restaurant_app.reservation.models
restaurant_app.reservation.service_test --> restaurant_app.reservation.service
restaurant_app.restaurant.service --> restaurant_app.restaurant.models
restaurant_app.restaurant.service --> restaurant_app.restaurant.service_model_mapper
restaurant_app.restaurant.service_model_mapper --> restaurant_app.restaurant.models
restaurant_app.restaurant.service_test --> restaurant_app.restaurant.service
restaurant_app.restaurant.views --> restaurant_app.restaurant.forms
restaurant_app.restaurant.views --> restaurant_app.restaurant.models
restaurant_app.restaurant.views --> restaurant_app.restaurant.service
restaurant_app.store.entities --> restaurant_app.store.database
restaurant_app.store.menu_repository --> restaurant_app.store.base_repository
restaurant_app.store.menu_repository --> restaurant_app.store.entities
restaurant_app.store.menu_repository_test --> restaurant_app.store.entities
restaurant_app.store.menu_repository_test --> restaurant_app.store.menu_repository
restaurant_app.store.menu_repository_test --> restaurant_app.store.repository_test_helpers
restaurant_app.store.menu_repository_test --> restaurant_app.store.restaurant_repository
restaurant_app.store.repository_test_helpers --> restaurant_app.store.database
restaurant_app.store.repository_test_helpers --> restaurant_app.store.entities
restaurant_app.store.reservation_repo --> restaurant_app.store.base_repository
restaurant_app.store.reservation_repo --> restaurant_app.store.entities
restaurant_app.store.reservation_repo_test --> restaurant_app.store.entities
restaurant_app.store.reservation_repo_test --> restaurant_app.store.repository_test_helpers
restaurant_app.store.reservation_repo_test --> restaurant_app.store.reservation_repo
restaurant_app.store.reservation_repo_test --> restaurant_app.store.restaurant_repository
restaurant_app.store.reservation_repo_test --> restaurant_app.store.table_repository
restaurant_app.store.restaurant_repository --> restaurant_app.store.base_repository
restaurant_app.store.restaurant_repository --> restaurant_app.store.entities
restaurant_app.store.restaurant_repository_test --> restaurant_app.store.repository_test_helpers
restaurant_app.store.restaurant_repository_test --> restaurant_app.store.restaurant_repository
restaurant_app.store.table_repository --> restaurant_app.store.base_repository
restaurant_app.store.table_repository --> restaurant_app.store.entities
restaurant_app.store.table_repository_test --> restaurant_app.store.entities
restaurant_app.store.table_repository_test --> restaurant_app.store.repository_test_helpers
restaurant_app.store.table_repository_test --> restaurant_app.store.restaurant_repository
restaurant_app.store.table_repository_test --> restaurant_app.store.table_repository
@enduml
