from random import randint

# as usual: solution found @ stackoverflow
#   https://stackoverflow.com/questions/2673385/how-to-generate-a-random-number-with-a-specific-amount-of-digits
# or not so usual these days, because it was not generated by an LLM.
# the result of ChatGPT is quite similar:
#
# Here's a function that generates a random number with the length specified by the given integer:
#
# import random
#
# def generate_random_number(length):
#     if length <= 0:
#         return "Length must be a positive integer."

#     # Generate a random number of specified length
#     # The range starts at 10^(length-1) to ensure the correct length and ends at (10^length) - 1
#     random_number = random.randint(10**(length - 1), 10**length - 1)

#     return random_number

# # Example usage
# length = 5
# print(generate_random_number(length))


def random_with_N_digits(n):
    range_start = 10 ** (n - 1)
    range_end = (10**n) - 1
    return randint(range_start, range_end)
