# basic flask app settings
STATIC_FOLDER: "static"
TEMPLATES_FOLDER: templates"
FLASK_ENV: "production"
DEBUG: false
TESTING: false

# database settings
DATABASE_URI: "sqlite:///app.db"
DATABASE_ECHO: false
