# basic flask app settings
FLASK_ENV: "production"
DEBUG: false
TESTING: false
SECRET_KEY: very-secret-key

# database settings
DATABASE_URI: "sqlite:///app.db"
#DATABASE_URI: "mariadb+pymysql://root:root-password@localhost/RESTAURANTS?charset=utf8mb4"
DATABASE_ECHO: false
